pipeline {
    agent any
    parameters {string(name: 'reponame', defaultValue: '', description: '') }
    tools {
        maven 'Maven'
    }
    stages {
        stage ('incremental version') {
         steps {
             script{
            // def reponame = "samehpalas/demo-app"  //instead, value as an input from the customer as shown above
             def version = "0"
             def tag= "$version-$BUILD_NUMBER" // to increase image dynamically according to build number
             env.imagename = "$reponame:$tag"
          }
         }
    }
     // stage('buildJAR') {
     //     steps {
     //        echo 'building the Application... '
     //        sh 'mvn package'
    //     }
    //  }
        
        stage('buildIMG') {
            steps {
                echo 'Building the docker image... '
                withCredentials([usernamePassword(credentialsId: 'sameh-dockerhub-cred', usernameVariable: 'USER', passwordVariable: 'PASS')])
                 {
                   sh " docker build -t $imagename simplefile_Examples/versioning/ "
                   sh " echo $PASS | docker login -u $USER --password-stdin "
                   sh " docker push $imagename "
            }
            }
        }
        
        stage('deploy') {
            steps {
                echo 'Deploying the Application... '
            }
        }
        
    }
}
