pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage ('incremental version') {
         steps {
             def reponame = "samehpalas/demo-app"
             def version = "0"
             def tag= "$version-$BUILD_NUMBER"
             env.imagename = "$reponame+$tag"
         }
    }
     // stage('buildJAR') {
     //     steps {
     //        echo 'building the Application... '
     //        sh 'mvn package'
    //     }
    //  }
        
        stage('buildIMG') {
            steps {
                echo 'Building the docker image... '
                withCredentials([usernamePassword(credentialsId: 'sameh-dockerhub-cred', usernameVariable: 'USER', passwordVariable: 'PASS')])
                 {
                   sh ' docker build -t $imagename simplefile_Examples/versioning/ '
                   sh ' echo $PASS | docker login -u $USER --password-stdin '
                   sh ' docker push $imagename '
            }
            }
        }
        
        stage('deploy') {
            steps {
                echo 'Deploying the Application... '
            }
        }
        
    }
}
