pipeline {
    agent any
    
    stages {
        stage('build') {
            when {
                expression {
                    BRANCH_NAME == 'dev' && CODE_CHANGES ==true
                }
            }
            steps {
                echo 'building the Application... '
            }
        }
        
        stage('test') {
            when {
                expression {
                    BRANCH_NAME == 'dev'
                }
            }
            steps {
                echo 'TeStInG the Application... '
            }
        }
        
        stage('deploy') {
            steps {
                echo 'Deploying the Application... '
            }
        }
        
    }
}
