pipeline {
    agent any
    environment {
        NEW_VERSION = "1.3.0"
        CREDENTIALS= credentials ('sameh-dockerhub-cred')
    }
    stages {
        stage('build') {
            steps {
                echo 'building the Application... '
                echo "version is ${NEW_VERSION} "
            }
        }
        
        stage('test') {
            steps {
                echo 'TeStInG the Application... '
                echo "cred ysta is here ${sameh-dockerhub-cred}"
            }
        }
        
        stage('deploy') {
            steps {
                echo "cred ysta is here ${sameh-dockerhub-cred}"
                echo 'Deploying the Application... '
            }
        }
        
    }
}
